### PR TITLE
Support alb

### PR DESCRIPTION
**Pull request by umatrangolo**
This will add support for the new ALB in Amazon.

*Will work only with Nova 1.2.0+*

### CODE REVIEW

**Comment by gheine** [comment]
Oh sorry. ALB? Should we look at transitioning from ELB to NLB? Maybe 2.0 can be ALB and 3.0 can be NLB?

**Comment by umatrangolo** [comment]
Here you go Sir

**Comment by umatrangolo** [comment]
@gheine Please review

**Comment by umatrangolo** [comment]
Please note that ALB and NLB are for different use cases.

We are gonna use ALBs AFAIK (layer7).

**Comment by umatrangolo** [comment]
@gheine Done

**Comment by umatrangolo** [comment]
@gheine Please review

**Pull request merged**
