### PR TITLE
Remove public IP addresses from EC2 instances

### PR DESCRIPTION
**Pull request by kevinoriordan**
Don't see why there's a need for our EC2 instances to be visible from the outside world (all access through either be through an SSH bastion or via load balancer). And Amazon GuardDuty indicates that open ports on the instances are being actively probed outside so there is a security risk.

### CODE REVIEW

**Comment by brazir** [comment]
LGTM

**Comment by andreyk0** [comment]
IIRC the original motivation for using public IPs was because not all AWS services supported VPC endpoints and so traffic went through NAT gateway, which also was not particularly great at the time.
When instances have public IPs (and yes, obviously they need to be protected by nacls and security groups to avoid outside access) they can talk to AWS infrastructure more directly (no limits / extra latency due to NAT).

**Comment by kevinoriordan** [comment]
It seems in the case of Nova deployed services we were getting the worst of both worlds as the instances were still assigned private subnets so I'm 90% sure traffic was going through the NAT instance/gateway anyway. I'm basing that partially on my reading of the AWS docs but mostly on an outage we had some time ago where we tried to deploy too many Nova services at the same time and the deployments were failing due to the NAT instance being saturated when trying to pull the images from S3. All those instances had public IPs if I recall correctly but private subnets.

As an aside, we switched from NAT instances to NAT gateways after the outage which should alleviate the saturation issue a good bit. Also, we should probably configure VPC endpoints for S3 and DynamoDB so we don't have to go through the NAT gateway for those services.

I checked how security groups work with Nova and it seems service owners have to specify a security group rather than relying on sensible defaults. In the case of the warnings we were getting, it looked like the security groups were too permissive. 

I guess we should test this out on a high traffic service and see if we notice any performance degradation.

**Comment by andreyk0** [comment]
Yeah, situation is very different now, there are a lot more options. From VPC-private service endpoints for many more services to a proper managed NAT gateway, definitely worth reviewing this stuff.

I vaguely remember that we used to rely on this at some point, maybe when we first moved in to AWS. I think mobile was the first account but even it now has NAT gateways, so, yeah, seems ripe for cleanup.

This goes beyond nova, I imagine, you may want to send an email to tech highlighting this issue.

**Comment by kevinoriordan** [comment]
Going to merge this and then send out the mail.

**Pull request merged**
